"$schema" = "node_modules/wrangler/config-schema.json"
name = "tigf"
# Set this to today's date
compatibility_date = "2026-04-14"
compatibility_flags = [ "nodejs_compat" ]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = true

# Production
[env.production]
name = "tigf"
workers_dev = true

# Develop
[env.develop]
name = "tigf-v2-dev"
workers_dev = true